## IMPORTING DATA THROUGH PANDAS

In [2]:
import pandas as pd

customers = pd.read_csv('Customers.csv', encoding='latin-1')

In [26]:
data_dictionary = pd.read_csv('Data_Dictionary.csv', encoding='latin-1')
exchange_rate = pd.read_csv('Exchange_Rates.csv', encoding='latin-1')
products = pd.read_csv('Products.csv', encoding='latin-1')
sales = pd.read_csv('Sales.csv', encoding='latin-1')
stores = pd.read_csv('Stores.csv', encoding='latin-1')

## CLEANING DATA TABLE-WISE

### PRODUCTS TABLE

In [54]:
products
products['Unit Cost USD'] = products['Unit Cost USD'].str.replace('$', '')
products['Unit Price USD'] = products['Unit Price USD'].str.replace('$', '')

In [56]:
products.rename(columns = {'ProductKey':'product_key',
                           'Product Name' : 'product_name',
                           'Brand' : 'brand',
                           'Color' : 'color',
                           'Unit Cost USD' : 'unit_cost_usd',
                           'Unit Price USD' : 'unit_price_usd',
                           'SubcategoryKey' : 'subcategory_key',
                           'Subcategory' : 'subcategory',
                           'CategoryKey' : 'category_key',
                           'Category' : 'category'
                           }, inplace=True)

In [ ]:
products['unit_price_usd'] = pd.to_numeric(products['unit_price_usd'], errors='coerce')
products['unit_cost_usd'] = pd.to_numeric(products['unit_cost_usd'], errors='coerce')

# Check the data types
print(products.dtypes)

### EXCHANGE RATE TABLE

In [34]:
exchange_rate['Date'] = pd.to_datetime(exchange_rate['Date'])

In [59]:
exchange_rate.rename(columns = {
    'Date': 'date',
    'Currency': 'currency',
    'Exchange': 'exchange'
}, inplace=True)

### SALES TABLE

In [62]:
sales['Order Date'] = pd.to_datetime(
    sales['Order Date'],
    dayfirst=True,
    errors='coerce'
)
sales['Delivery Date'] = pd.to_datetime(
    sales['Delivery Date'],
    dayfirst=True,
    errors='coerce'
)
sales.rename(columns = {
    'Order Number': 'order_number',
    'Line Item': 'line_item',
    'Order Date': 'order_date',
    'Delivery Date': 'delivery_date',
    'CustomerKey': 'customer_key',
    'StoreKey': 'store_key',
    'ProductKey': 'product_key',
    'Quantity': 'quantity',
    'Currency Code': 'currency_code'
}, inplace=True)

In [63]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_number   62884 non-null  int64
 1   line_item      62884 non-null  int64
 2   order_date     24344 non-null  datetime64[ns]
 3   delivery_date  7916 non-null   datetime64[ns]
 4   customer_key   62884 non-null  int64
 5   store_key      62884 non-null  int64
 6   product_key    62884 non-null  int64
 7   quantity       62884 non-null  int64
 8   currency_code  62884 non-null  object
dtypes: datetime64[ns](2), int64(6), object(1)
memory usage: 4.3+ MB

In [84]:
sales['delivery_date'].isna().sum()

AttributeError: 'Series' object has no attribute 'isnotna'

### STORES TABLE

In [66]:
stores.rename(columns = {
    'StoreKey': 'store_key',
    'Country': 'country',
    'State': 'state',
    'Square Meters': 'square_meters',
    'Open Date': 'open_date'
}, inplace=True)

In [68]:
stores['open_date'] = pd.to_datetime(stores['open_date'], dayfirst = True, errors = 'coerce')

In [69]:
stores.head()

,store_key,country,state,square_meters,open_date
0,1,Australia,Australian Capital Territory,595.0,2008-01-01
1,2,Australia,Northern Territory,665.0,2008-12-01
2,3,Australia,South Australia,2000.0,2012-07-01
3,4,Australia,Tasmania,2000.0,2010-01-01
4,5,Australia,Victoria,2000.0,2015-09-12

## CUSTOMERS TABLE

In [75]:
customers.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [76]:
customers.rename(columns = {
    'CustomerKey': 'customer_key',
    'Gender': 'gender',
    'Name': 'name',
    'City': 'city',
    'State Code': 'state_code',
    'State': 'state',
    'Zip Code': 'zip_code',
    'Country': 'country',
    'Continent': 'continent',
    'Birthday': 'birthday'
}, inplace=True)

In [78]:
customers['birthday'] = pd.to_datetime(customers['birthday'],
                                      dayfirst = True,
                                      errors = 'coerce')

# EXPORTING THE DATA TO MS SQL DATABASE FOR E.D.A

In [73]:
# creating the connection, engine creates the blueprint of the connection
# my database name is global_elec
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mssql+pyodbc://@localhost\\SQLEXPRESS/global_elec?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&TrustServerCertificate=yes")

In [80]:
customers.to_sql(name='customers', con = engine, index = False)
sales.to_sql(name='sales', con = engine, index = False)
products.to_sql(name='products', con = engine, index = False)
stores.to_sql(name='stores', con = engine, index = False)
data_dictionary.to_sql(name='data_dictionary', con = engine, index = False)
exchange_rate.to_sql(name='exchange_rate', con = engine, index = False)

9

In [1]:
## new